spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      port: 27017
      host: 172.22.0.2
      database: springhost
  mvc:
    format:
      time: HH:mm
keycloak:
  realm: spring-realm
  auth-server-url: http://localhost:10002/auth
  resource: routines
  public-client: true
  security-constraints[0]: 
    authRoles[0]: user
    securityCollections[0]:
      patterns[0]: /*

server:
  port: 10004
