version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "10001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    networks:
      backend:
        aliases:
          - "mysql"
  keycloak:
    image: jboss/keycloak
    restart: always
    ports:
      - "10002:8080"
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - DB_DATABASE=keycloak
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_USER=root
      - DB_VENDOR=mysql
    volumes:
        - ./realm-export.json:/opt/jboss/keycloak/realm-export.json
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json"
      - "-Dkeycloak.profile.feature.scripts=enabled"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    networks:
      backend:
        aliases:
          - "keycloak"
networks:
  backend:
    driver: bridge